import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    kotlin("multiplatform") version "2.4.20"
    `maven-publish`
}

group = (findProperty("group") as? String) ?: "io.github.persiancalendar"
version = (findProperty("version") as? String) ?: "1.4.0"

repositories {
    mavenCentral()
}

val generatedTestResourcesDir = layout.buildDirectory.dir("generated/kotlin/testResources")

val generateTestResources = tasks.register("generateTestResources") {
    val resourcesDir = file("src/test/resources")

    inputs.dir(resourcesDir)
    outputs.dir(generatedTestResourcesDir)

    doLast {
        val resources = listOf(
            "leaps" to "leaps.txt",
            "khaterat" to "khaterat-e-etemad-ol-saltane.txt",
            "sarlati" to "Sarlati.txt",
            "calendarCenterData" to "CalendarCenterData.txt",
            "oldEraPersianCalendar" to "OldEraPersianCalendar.txt",
            "qamariPredictions" to "qamari-perdictions.txt",
            "qamariConsolidated" to "qamari/consolidated.txt",
        )

        val content = buildString {
            appendLine("package io.github.persiancalendar.calendar")
            appendLine()
            appendLine("// Generated by Gradle from src/test/resources. Do not edit.")
            appendLine("internal object TestResources {")
            for ((name, path) in resources) {
                val text = resourcesDir.resolve(path).takeIf { it.exists() }?.readText()
                    ?: error("Missing test resource $path (run `git submodule update --init`?)")
                require("\"\"\"" !in text) { "Resource contains a raw-string delimiter: $path" }
                val safeText = text.replace("$", "\${'$'}")
                appendLine("    val $name = \"\"\"$safeText\"\"\"")
            }
            appendLine("}")
        }

        val file = generatedTestResourcesDir.get()
            .file("io/github/persiancalendar/calendar/TestResources.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(content)
    }
}

kotlin {
    jvmToolchain(21)

    jvm {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_21
        }
    }

    js {
        nodejs()
        browser()
    }

    linuxArm64()
    linuxX64()
    macosArm64()
    mingwX64()

    sourceSets {
        commonTest {
            kotlin.srcDir(generatedTestResourcesDir)
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

tasks.matching { it.name.startsWith("compileTestKotlin") }.configureEach {
    dependsOn(generateTestResources)
}

tasks.withType<org.gradle.api.tasks.testing.AbstractTestTask>().configureEach {
    testLogging {
        showStandardStreams = true
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.targets.js.testing.KotlinJsTest>().configureEach {
    useMocha {
        // A few conversion tests loop over very large JDN ranges and are slow
        // under Node, so allow them plenty of time.
        timeout = "10m"
    }
}
